Update imports after ftw.shop udpate.
4teamwork/ftwshop.simplelayout pull request #20
Opened 2017-05-10 12:58 UTC by shylux

In `ftw.shop` the previous default view got removed and replaced by the compact view, renaming compact view to default.
This pr just updates the import for this change which is not yet released but on `ftw.shop` `master`.

2017-06-19 08:51 UTC, lukasgraf requested changes
Changelog entry missing

2017-06-19 08:51 UTC, lukasgraf commented on development.cfg
> +eggs += simplelayout.types.common
What is this for?

2017-06-19 08:51 UTC, lukasgraf commented on ftwshop/simplelayout/browser/shopitemblock.py
> +from ftw.shop.browser.shopitem import ShopItemView
Since this change is going to be backwards incompatible, there should be a version constraint in `setup.py` on the appropriate required version of `ftw.shop`

2017-06-26 08:10 UTC, shylux commented on development.cfg
> +eggs += simplelayout.types.common
I added this because i needed a container to add the shopitem block. I split this into a separate commit.

2017-06-26 08:11 UTC, shylux commented on ftwshop/simplelayout/browser/shopitemblock.py
> +from ftw.shop.browser.shopitem import ShopItemView
Released `ftw.shop` and updated constraint.

2017-06-26 08:12 UTC, shylux commented
@lukasgraf also added changelog entries

2017-06-26 08:14 UTC, lukasgraf approved these changes

2017-06-26 08:14 UTC, lukasgraf commented
LGTM 👍

2017-06-26 08:15 UTC, merged